### PR TITLE
Fix some Javascript bugs that have popped up

### LINKED ISSUE #109: JS register method displays the wrong error message if output element isn't queryable
Repro:
Register Stork on a page with the following HTML:

```html
<div class="stork-wrapper">
    <input data-stork="federalist" class="stork-input" />
    <div class="stork-output"></div>
</div>
```

Error message in console will reference a missing input element, not a missing output element.

### LINKED ISSUE #116: Stork JS adds a <ul> to the dom while the index is loading
Something in the DOM logic is making it so the output div has a `<ul class="stork-results">` child until Stork fully loads, at which point the child is removed from the DOM. This is a little rough, because the default theme has some styling that makes that `<ul>` visible.

You can see this on <https://jameslittle.me>, and it looks pretty rough.

- [ ] Fix this bug, but then...
- [ ] Figure out why this wasn't affecting the test setup

### PR DESCRIPTION
**Pull request by jameslittle230**
This:
- Fixes #116 
- Fixes #109 
- Removes some stray console output
- Fixes error states after loading the index so it doesn't try to load an index that's a 404 page

### CODE REVIEW

File: js/entityManager.ts [hunk 1]
```diff
@@ -15,30 +15,33 @@ export class EntityManager {
...
+          entity.name,
+          new Uint8Array(response)
+        );
 
-      entity.performSearch(entity.domManager.getQuery());
+        entity.setDownloadProgress(1);
+        entity.performSearch(entity.domManager.getQuery());
 
-      if (entity.config.printIndexInfo) {
-        this.wasmQueue.runAfterWasmLoaded(() => {
```
Comment (jameslittle230) [inline js/entityManager.ts:34]: This seemed... completely unnecessary, so I'm removing it. This might come back to bite me, but hopefully it doesn't!
